# Generated by Django 4.2.2 on 2023-07-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontlyKillSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('frontly_killswitch', 'Can activate frontly kill switch'),),
                'managed': False,
            },
        ),
    ]
